#!/bin/bash

set -e

charm="$1"
branch="$2"

if [ -z "$charm" ] || [ -z "$branch" ]; then
    echo "Usage: charm-git-import charm-name branch"
    exit 1
fi

echo "Initializing git repo"
mkdir $charm
cd $charm
git init

echo "Exporting bzr branch to git"
bzr fast-export --plain $branch| git fast-import
git reset --hard HEAD
git filter-branch --commit-filter '
    if [ "$GIT_COMMITTER_NAME" = "james.page@ubuntu.com" ]; then
        GIT_COMMITTER_NAME="James Page" GIT_COMMITTER_EMAIL="james.page@ubuntu.com"
    fi
    if [ "$GIT_AUTHOR_NAME" = "james.page@ubuntu.com" ]; then
        GIT_AUTHOR_NAME="James Page" GIT_AUTHOR_EMAIL="james.page@ubuntu.com"
    fi
    git commit-tree "$@"' HEAD

# Rename the ignore file to where git expects
git mv .bzrignore .gitignore || :

# Default rule in bzr missing in git for editor swap files
echo "*.sw[nop]" >> .gitignore
git commit -am "Adapt imports and metadata for github move"

# Cargo culted repo packing
git gc --aggressive --prune=now

# Propogate repo
git remote add origin git@github.com:openstack-charmers/$(basename $charm).git
git checkout -b stable $(cat ../stable.txt) || :

# Current github user needs push rights
# git push --force -u origin master
