#!/bin/bash

set -e

charms=$(cat ../charms.txt)

mkdir -p bzr

for charm in $charms; do
  if [ -d bzr/$charm ]; then
    (cd bzr/$charm; bzr pull)
  else
    bzr branch lp:~openstack-charmers/charms/trusty/$charm/next bzr/$charm
  fi
done
