#!/bin/bash

set -e

charms=$(grep -v '#' ../charms.txt)
blacklist=$(grep -v '#' blacklist.txt || :)

mkdir -p bzr

for charm in $charms; do
  if [[ $blacklist == *$charm* ]]; then
    echo " ! Skipping blacklisted:  $charm"
    continue
  fi
  if [ -d bzr/$charm ]; then
    (cd bzr/$charm; bzr pull)
  else
    bzr branch lp:~openstack-charmers/charms/trusty/$charm/next bzr/$charm
  fi
done
