#!/bin/bash -e

echo "===== $(basename $0) ====="

bzr_dir="$1"
git_dir="$2"

if [ -z "$bzr_dir" ] || [ -z "$git_dir" ]; then
    echo "Usage: charm-bzr-import bzr-dir git-dir"
    exit 1
fi

root_dir=`pwd`
charm=$(basename $bzr_dir)

# Determine if stable or next charm
if [[ "$bzr_dir" == *"/stable/$charm" ]]; then
    stable=true
else
    stable=false
fi

echo " . Exporting $git_dir (stable: $stable)"
tmp_dir=$root_dir/tmp
mkdir -p $tmp_dir
cd $root_dir/$git_dir

branches_all="$(git branch -a)"
current_stable=$(cat $root_dir/../stable.txt)
stable_remote="remotes/origin/stable/${current_stable}"
export_file="$tmp_dir/${charm}.fi"

if [ "$charm" == "swift-proxy" ]; then
    extra_flags="--full-tree"
fi

if [ "$stable" == true ] && [[ "$branches_all" == *"$stable_remote"* ]]; then
    git fast-export ${extra_flags} ${stable_remote} > $export_file
elif [ "$stable" == true ] && [[ "$branches_all" != *"$stable_remote"* ]]; then
    echo " ! Skipping $git_dir (No $stable_remote)"
    exit 0
else
    git fast-export ${extra_flags} master > $export_file
fi

echo " . Initializing bzr repo $bzr_dir"
mkdir -p $bzr_dir
cd $bzr_dir
bzr init

echo " . Importing to $bzr_dir (stable: $stable)"
bzr fast-import $export_file $bzr_dir

echo " + Setting bzr repo parent location"
cd $bzr_dir
if [ "$stable" == "true" ]; then
    bzr config parent_location="bzr+ssh://bazaar.launchpad.net/~openstack-charmers/charms/trusty/$charm/trunk"
else
    bzr config parent_location="bzr+ssh://bazaar.launchpad.net/~openstack-charmers/charms/trusty/$charm/next"
fi
bzr config parent_location
