#!/bin/bash -e

echo "===== $(basename $0) ====="

charms=$(grep -v '#' ../charms.txt)
blacklist=$(grep -v '#' blacklist.txt || :)

mkdir -p bzr/current/{next,stable}

for charm in $charms; do
  if [[ $blacklist == *$charm* ]]; then
    echo " ! Skipping blacklisted:  $charm"
    continue
  fi
  if [ -d github/charm-$charm ]; then
    echo " . Pulling from https://github.com/openstack/charm-$charm"
    (cd github/charm-$charm; git pull)
  else
    echo " . Cloning from https://github.com/openstack/charm-$charm"
    git clone https://github.com/openstack/charm-$charm github/charm-$charm
  fi

  # get the current bzr branches
  bzr branch "bzr+ssh://bazaar.launchpad.net/~openstack-charmers/charms/trusty/$charm/trunk" \
      `pwd`/bzr/current/stable/$branch/$charm
  bzr branch "bzr+ssh://bazaar.launchpad.net/~openstack-charmers/charms/trusty/$charm/next" \
      `pwd`/bzr/current/next/$branch/$charm
done
