#!/bin/bash

set -e

charms=$(cat ../charms.txt)
rm -rf bzr
mkdir -p bzr/{next,stable}

for charm in $charms; do
    for branch in next stable; do
        ./charm-bzr-import `pwd`/bzr/$branch/$charm github/charm-$charm
    done
done
