#!/bin/bash -e

echo "===== $(basename $0) ====="

for charm in `ls -1 bzr/stable/`; do
    echo " + Pushing $charm stable charm"
    if [ -d bzr/stable/$charm ]; then
        (
            cd bzr/stable/$charm
            echo "$(pwd) --> $(bzr config parent_location)"
            bzr push --overwrite :parent
        )
    fi
done
for charm in `ls -1 bzr/next/`; do
    echo " + Pushing $charm next charm"
    if [ -d bzr/next/$charm ]; then
        (
            cd bzr/next/$charm
            echo "$(pwd) --> $(bzr config parent_location)"
            bzr push --overwrite :parent
        )
    fi
done
